# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: AD63CD24-1548-44A4-B13E-708163EA9B2E;libbacktrace;no-cmake-loader,no-cmake-platform-windows,no-cmake-searchpath,no-craft-platform-windows,no-import,no-public,no-require;backtrace
# Disable with : `mulle-sourcetree mark libbacktrace no-link`
# Disable for this platform: `mulle-sourcetree mark libbacktrace no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark libbacktrace no-cmake-sdk-<name>`
#
if( NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
   if( COLLECT_ALL_LOAD_DEPENDENCY_LIBRARIES_AS_NAMES)
      list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES "backtrace")
   else()
      if( NOT LIBBACKTRACE_LIBRARY)
         find_library( LIBBACKTRACE_LIBRARY NAMES
            ${CMAKE_STATIC_LIBRARY_PREFIX}backtrace${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}backtrace${CMAKE_STATIC_LIBRARY_SUFFIX}
            backtrace
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT LIBBACKTRACE_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( LIBBACKTRACE_LIBRARY NAMES
               ${CMAKE_STATIC_LIBRARY_PREFIX}backtrace${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}backtrace${CMAKE_STATIC_LIBRARY_SUFFIX}
               backtrace
            )
         endif()
         message( STATUS "LIBBACKTRACE_LIBRARY is ${LIBBACKTRACE_LIBRARY}")
         #
         # The order looks ascending, but due to the way this file is read
         # it ends up being descending, which is what we need.
         #
         if( LIBBACKTRACE_LIBRARY)
            #
            # Add LIBBACKTRACE_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
            # Disable with: `mulle-sourcetree mark libbacktrace no-cmake-add`
            #
            list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES ${LIBBACKTRACE_LIBRARY})
            #
            # Inherit information from dependency.
            # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
            # Disable with: `mulle-sourcetree mark libbacktrace no-cmake-inherit`
            #
            # temporarily expand CMAKE_MODULE_PATH
            get_filename_component( _TMP_LIBBACKTRACE_ROOT "${LIBBACKTRACE_LIBRARY}" DIRECTORY)
            get_filename_component( _TMP_LIBBACKTRACE_ROOT "${_TMP_LIBBACKTRACE_ROOT}" DIRECTORY)
            #
            #
            # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
            # Disable with: `mulle-sourcetree mark libbacktrace no-cmake-dependency`
            #
            foreach( _TMP_LIBBACKTRACE_NAME "backtrace")
               set( _TMP_LIBBACKTRACE_DIR "${_TMP_LIBBACKTRACE_ROOT}/include/${_TMP_LIBBACKTRACE_NAME}/cmake")
               # use explicit path to avoid "surprises"
               if( IS_DIRECTORY "${_TMP_LIBBACKTRACE_DIR}")
                  list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_LIBBACKTRACE_DIR}")
                  #
                  include( "${_TMP_LIBBACKTRACE_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
                  #
                  list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_LIBBACKTRACE_DIR}")
                  #
                  unset( LIBBACKTRACE_DEFINITIONS)
                  include( "${_TMP_LIBBACKTRACE_DIR}/Definitions.cmake" OPTIONAL)
                  list( APPEND INHERITED_DEFINITIONS ${LIBBACKTRACE_DEFINITIONS})
                  break()
               else()
                  message( STATUS "${_TMP_LIBBACKTRACE_DIR} not found")
               endif()
            endforeach()
         else()
            # Enable with: `mulle-sourcetree mark libbacktrace require`
            message( STATUS "LIBBACKTRACE_LIBRARY is missing but it is marked as \"no-require\"")
         endif()
      endif()
   endif()
endif()


#
# Generated from sourcetree: BF506244-6FB2-4368-984F-65E0A270B2D2;mulle-core;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import;
# Disable with : `mulle-sourcetree mark mulle-core no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-core no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-core no-cmake-sdk-<name>`
#
if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND DEPENDENCY_LIBRARIES "mulle-core")
else()
   if( NOT MULLE__CORE_LIBRARY)
      find_library( MULLE__CORE_LIBRARY NAMES
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core${CMAKE_STATIC_LIBRARY_SUFFIX}
         mulle-core
         NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
      )
      if( NOT MULLE__CORE_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
         find_library( MULLE__CORE_LIBRARY NAMES
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core${CMAKE_STATIC_LIBRARY_SUFFIX}
            mulle-core
         )
      endif()
      message( STATUS "MULLE__CORE_LIBRARY is ${MULLE__CORE_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE__CORE_LIBRARY)
         #
         # Add MULLE__CORE_LIBRARY to DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-core no-cmake-add`
         #
         list( APPEND DEPENDENCY_LIBRARIES ${MULLE__CORE_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-core no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__CORE_ROOT "${MULLE__CORE_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__CORE_ROOT "${_TMP_MULLE__CORE_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-core no-cmake-dependency`
         #
         foreach( _TMP_MULLE__CORE_NAME "mulle-core")
            set( _TMP_MULLE__CORE_DIR "${_TMP_MULLE__CORE_ROOT}/include/${_TMP_MULLE__CORE_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__CORE_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__CORE_DIR}")
               #
               include( "${_TMP_MULLE__CORE_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__CORE_DIR}")
               #
               unset( MULLE__CORE_DEFINITIONS)
               include( "${_TMP_MULLE__CORE_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__CORE_DEFINITIONS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__CORE_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark mulle-core no-require-link`
         message( SEND_ERROR "MULLE__CORE_LIBRARY was not found in ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core${CMAKE_STATIC_LIBRARY_SUFFIX}
mulle-core")
      endif()
   endif()
endif()
